/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as cpammSol from "./CPAMM.sol";

export type { cpammSol };
export type { Counter } from "./Counter";
export type { EncryptedERC20 } from "./EncryptedERC20";
