/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as fheOsSol from "./FheOS.sol";
import type * as access from "./access";

export type { fheOsSol };

export type { access };
export type { FHE } from "./FHE";
